services:
  - type: web
    name: taskmaster
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py app:app"
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: your-db-name
      - key: SECRET_KEY
        value: your-secret-key
      - key: MAIL_USERNAME
        value: your-email
      - key: MAIL_PASSWORD
        value: your-email-password
      - key: PORT
        value: 10000
