services:
  - type: web
    name: taskmaster
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py app:app"
    envVars:
      - key: DB_HOST
        value: 172.29.187.8
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: remote_user
      - key: DB_PASSWORD
        value: hmoodecr1o
      - key: DB_NAME
        value: task_manager
      - key: SECRET_KEY
        value: Hmoodecr10engbekoo10
      - key: MAIL_USERNAME
        value: altyebwebsite@gmail.com
      - key: MAIL_PASSWORD
        value: ufbu vbqk ykvl lpgn
      - key: PORT
        value: 10000  # The port your web service should listen on
      - key: WEB_CONCURRENCY
        value: 1  # Number of Gunicorn workers
